### ISSUE TITLE
Snap timeline bracket when close to where video is stopped

### ISSUE THREAD

**Issue by psociety** [mat-sz/crop#2]
When cutting the video i let it play and i press space where i want to cut it so i have a guide at the top on where i should place the timeline bracket.

It would be helpful if the bracket snapped where the stop position is when close to it.

https://github.com/user-attachments/assets/c2336328-778b-4d47-9f2b-5fd1d17257aa

**Comment by mat-sz** [comment]
@psociety Thank you for your suggestion. This feature has been added in cb9e0e63e1fd38fc73e9664f5cddb9cf4bb9112a and is now live.
